name: Tagged Release

on:
    push:
        tags:
            - 'v*'

jobs:
    tagged-release:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      name: 'Tagged Release'
      runs-on: 'ubuntu-latest'
      steps:
#            - name: 'Publish release'
#              uses: 'marvinpinto/action-automatic-releases@latest'
#              with:
#                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
#                  prerelease: false
#                  files: |
#                      LICENSE.txt
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Node
          uses: actions/setup-node@v3
          with:
              node-version: 20
              registry-url: https://registry.npmjs.org/

        - name: Install dependencies
          run: npm ci

        - name: Build
          run: npm run build:npm

        - name: npm publish
          run: npm publish
          env:
              NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

